#ifndef CONSTANTS_H
#define CONSTANTS_H

#define PLAYER_START_SPEED 0.0f;
#define PLAYER_START_ACCELERATION 0.0f;
#define PLAYER_MAX_SPEED 200.0f;
#define PLAYER_RADIUS 15.0f;
#define PLAYER_ACCELERATION 0.1f;
#define PLAYER_MAX_ACCELERATION 1.2f;
#define PLAYER_MASS 1.0f;

#endif
